# Generated by Django 5.0.6 on 2026-06-30 12:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('FILE', 'File'), ('URL', 'URL')], max_length=8)),
                ('source_ref', models.CharField(max_length=2048)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled'), ('INCONCLUSIVE', 'Inconclusive')], default='QUEUED', max_length=16)),
                ('media_state', models.CharField(choices=[('PRESENT', 'Present'), ('PURGED', 'Purged')], default='PRESENT', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelEvaluation',
            fields=[
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset', models.CharField(default='FaceForensics++', max_length=128)),
                ('split', models.CharField(default='held-out test', max_length=128)),
                ('accuracy', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('meets_baseline', models.BooleanField(default=False)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('likelihood', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('state', models.CharField(choices=[('OK', 'Ok'), ('NO_AUDIO_SIGNAL', 'No audio signal'), ('AUDIO_ERROR', 'Audio error')], default='OK', max_length=20)),
                ('error_detail', models.CharField(blank=True, default='', max_length=1024)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_result', to='detection.analysissession')),
            ],
        ),
        migrations.CreateModel(
            name='FrameHeatmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frame_id', models.CharField(max_length=64)),
                ('overlay_png', models.BinaryField()),
                ('delivered', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_heatmaps', to='detection.analysissession')),
            ],
        ),
        migrations.CreateModel(
            name='FusionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('label', models.CharField(blank=True, choices=[('authentic', 'Authentic'), ('deepfake', 'Deepfake')], max_length=16, null=True)),
                ('modalities_used', models.CharField(blank=True, default='', max_length=64)),
                ('inconclusive', models.BooleanField(default=False)),
                ('threshold_used', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fusion_result', to='detection.analysissession')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confusion_matrix', models.JSONField()),
                ('precision', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('recall', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('f1_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='detection.modelevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='PurgeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=8)),
                ('retries', models.IntegerField(default=0)),
                ('verified_empty', models.BooleanField(default=False)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purge_record', to='detection.analysissession')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('FAILED', 'Failed')], max_length=16)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='detection.analysissession')),
            ],
        ),
        migrations.CreateModel(
            name='StreamEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.IntegerField()),
                ('type', models.CharField(choices=[('progress', 'Progress'), ('heatmap', 'Heatmap'), ('result', 'Result'), ('error', 'Error')], max_length=16)),
                ('payload', models.JSONField()),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_events', to='detection.analysissession')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='VisualResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_likelihood', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('state', models.CharField(choices=[('OK', 'Ok'), ('NO_VISUAL_SIGNAL', 'No visual signal'), ('VISUAL_ERROR', 'Visual error')], default='OK', max_length=20)),
                ('frames_analyzed', models.IntegerField(default=0)),
                ('faces_isolated', models.IntegerField(default=0)),
                ('error_detail', models.CharField(blank=True, default='', max_length=1024)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visual_result', to='detection.analysissession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='streamevent',
            constraint=models.UniqueConstraint(fields=('session', 'seq'), name='unique_session_seq'),
        ),
    ]
