# Generated by Django 5.0.6 on 2026-09-08 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationmetrics',
            name='roc_auc',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='frameheatmap',
            name='heatmap_png',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frameheatmap',
            name='original_png',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelevaluation',
            name='train_dataset',
            field=models.CharField(default='FaceForensics++', max_length=128),
        ),
        migrations.AddField(
            model_name='modelevaluation',
            name='variant',
            field=models.CharField(choices=[('multimodal', 'Multimodal'), ('visual_only', 'Visual-only'), ('audio_only', 'Audio-only')], default='multimodal', max_length=16),
        ),
    ]
